include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "lib/model/*.g.dart"
    - "lib/model/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true